
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
//    id("amphibians.kotlin-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `maven-publish`
    signing
}

// val ossrhUsername: String by project
// val ossrhPassword: String by project

version = "1.0.0"

// val dokkaJavadocJar =
//    tasks.register<Jar>("dokkaJavadocJar") {
// //        dependsOn(tasks.dokkaJavadoc)
// //        from(tasks.dokkaJavadoc.flatMap { it.outputDirectory })
// //        archiveClassifier.set("javadoc")
//    }
//
// publishing {
//    // Configure all publications
//    publications.withType<MavenPublication> {
//        // Stub javadoc.jar artifact
// //        from(components["kotlin"])
//        version = "0.1.0-alpha.0"
// //        artifact(tasks.kotlinSourcesJar)
//        artifact(
//            tasks.register("${name}JavadocJar", Jar::class) {
//                archiveClassifier.set("javadoc")
//                archiveAppendix.set(this@withType.name)
//            },
//        )
//
//        // Provide artifacts information required by Maven Central
//        pom {
//            name.set("Amphibians: Native API Generator")
//            description.set("React Native Plugin And WebView JSAPI Generator")
//            url.set("https://github.com/yidafu/amphibians")
//
//            licenses {
//                license {
//                    name.set("The Apache License, Version 2.0")
//                    url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
//                }
//            }
//            developers {
//                developer {
//                    id.set("dovyih")
//                    name.set("Dov Yih")
//                    email.set("me@yidafu.dev")
//                }
//            }
//
//            scm {
//                url.set("https://github.com/yidafu/amphibians")
//            }
//        }
//    }
//
//    repositories {
//        maven {
//            url = uri("https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/")
//            // 这里就是之前在issues.sonatype.org注册的账号
//            credentials {
//                username = ossrhUsername
//                password = ossrhPassword
//            }
//        }
//    }
// }
// //
// signing {
// //    if (project.hasProperty("signing.gnupg.keyName")) {
// //    }
// //    useGpgCmd()
//    sign(publishing.publications)
// }
